apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api-container
        image: nagp2024amcart0test0acr0.azurecr.io/amcart/catalog-api:1.0.2 # Replace with your ACR Image Path
        ports:
        - containerPort: 8080 # Port your app listens on
        env:
        - name: COSMOSDB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cosmosdb-connection-string # Name of your Kubernetes Secret
              key: connection-string # Key in the secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
spec:
  type: LoadBalancer # Or ClusterIP if internal only, or NodePort
  ports:
    - port: 8000 # External port
      targetPort: 8080 # Internal container port
  selector:
    app: catalog-api # Selects pods with this label